name: py385_sample_proj_app

channels:
    - defaults
    - psilons

dependencies:
    - pypigeonhole-build
    - python>=3.6
    - pip
    - coverage==5.3
    - conda-build
    - conda-verify
    - anaconda-client
    - pip:
        - psutil
        - pipdeptree
        - coverage-badge
        - twine
